// Centralized Seed Data for Indian Kirana & Supermarket
export const storeProfile = {
  id: 'store_royal_001',
  name: 'Apna Kirana & Supermarket',
  tagline: 'Fresh Groceries • Wholesale Rates • Fast Home Delivery',
  owner_name: 'Rajesh Sharma',
  phone: '+91 98765 43210',
  email: 'store@apnakirana.in',
  address: 'Shop No. 12, Main Market Road, Sector 4, Indirapuram, Ghaziabad, UP - 201014',
  gstin: '09AAECR1234F1Z8',
  upi_id: 'apnakirana@okhdfcbank',
  currency_symbol: '₹',
  min_order_value: 199,
  delivery_charge: 30,
  free_delivery_above: 499,
  estimated_delivery_mins: '30-45 mins',
  store_status: 'OPEN', // OPEN or CLOSED
  opening_time: '07:30',
  closing_time: '22:30',
  operating_days: 'Monday to Sunday (All 7 Days)',
  logo_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80',
  printer_width: '80mm', // '58mm' or '80mm'
  printer_connection: 'BROWSER_DIRECT',
};

export const sampleCategories = [
  { id: 'cat_rice', name: 'Rice & Grains', slug: 'rice-grains', icon: '🌾', sort_order: 1, image_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_pulses', name: 'Pulses & Dal', slug: 'pulses-dal', icon: '🥣', sort_order: 2, image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_flours', name: 'Flours & Atta', slug: 'flours-atta', icon: '🍞', sort_order: 3, image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_sugar_salt', name: 'Sugar & Salt', slug: 'sugar-salt', icon: '🧂', sort_order: 4, image_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_oils', name: 'Cooking Oil & Ghee', slug: 'cooking-oil-ghee', icon: '🫒', sort_order: 5, image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_spices', name: 'Spices & Masala', slug: 'spices-masala', icon: '🌶️', sort_order: 6, image_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_dryfruits', name: 'Dry Fruits & Nuts', slug: 'dry-fruits-nuts', icon: '🥜', sort_order: 7, image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_beverages', name: 'Tea & Coffee', slug: 'tea-coffee', icon: '☕', sort_order: 8, image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_snacks', name: 'Snacks & Biscuits', slug: 'snacks-biscuits', icon: '🍪', sort_order: 9, image_url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_dairy', name: 'Dairy & Bakery', slug: 'dairy-bakery', icon: '🥛', sort_order: 10, image_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_household', name: 'Cleaning & Household', slug: 'cleaning-household', icon: '🧼', sort_order: 11, image_url: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80' },
  { id: 'cat_personal', name: 'Personal Care', slug: 'personal-care', icon: '🧴', sort_order: 12, image_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80' },
];

export const sampleProducts = [
  {
    id: 'prod_basmati_rice',
    category_id: 'cat_rice',
    name: 'India Gate Royal Basmati Rice (Loose)',
    brand: 'India Gate',
    barcode: '8901030001015',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 72,
    selling_price: 92,
    mrp: 115,
    wholesale_price: 88,
    min_selling_price: 82,
    gst_percent: 0,
    stock: 120.500,
    reserved_stock: 0,
    min_stock: 15,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 1,
    photo_url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    description: 'Aged long-grain aromatic royal Basmati rice. Perfect for Biryani, Pulao, and daily family meals.',
  },
  {
    id: 'prod_sona_masoori',
    category_id: 'cat_rice',
    name: 'Sona Masoori Raw Rice (Loose)',
    brand: 'Swarna',
    barcode: '8901030001022',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 44,
    selling_price: 56,
    mrp: 65,
    wholesale_price: 52,
    min_selling_price: 49,
    gst_percent: 0,
    stock: 240.000,
    reserved_stock: 0,
    min_stock: 25,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=600&q=80',
    description: 'Lightweight, easily digestible, aromatic South Indian Sona Masoori rice, ideal for daily consumption.',
  },
  {
    id: 'prod_toor_dal',
    category_id: 'cat_pulses',
    name: 'Unpolished Desi Toor Dal / Arhar Dal (Loose)',
    brand: 'Kisan Fresh',
    barcode: '8901030002012',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 110,
    selling_price: 135,
    mrp: 160,
    wholesale_price: 128,
    min_selling_price: 120,
    gst_percent: 0,
    stock: 75.250,
    reserved_stock: 0,
    min_stock: 10,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 1,
    photo_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    description: 'Premium unpolished toor dal rich in natural protein, minerals, and authentic aroma.',
  },
  {
    id: 'prod_moong_dal',
    category_id: 'cat_pulses',
    name: 'Dhuli Moong Dal Yellow (Loose)',
    brand: 'Kisan Fresh',
    barcode: '8901030002029',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 95,
    selling_price: 118,
    mrp: 140,
    wholesale_price: 112,
    min_selling_price: 105,
    gst_percent: 0,
    stock: 55.750,
    reserved_stock: 0,
    min_stock: 8,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 0,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80',
    description: 'Cleaned yellow moong dal for khichdi, dal tadka, and nutritious soupy preparations.',
  },
  {
    id: 'prod_chana_dal',
    category_id: 'cat_pulses',
    name: 'Golden Chana Dal (Loose)',
    brand: 'Kisan Fresh',
    barcode: '8901030002036',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 68,
    selling_price: 84,
    mrp: 100,
    wholesale_price: 80,
    min_selling_price: 75,
    gst_percent: 0,
    stock: 62.000,
    reserved_stock: 0,
    min_stock: 10,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 0,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=600&q=80',
    description: 'High-fiber golden chana dal, carefully graded and stones-free.',
  },
  {
    id: 'prod_aashirvaad_atta',
    category_id: 'cat_flours',
    name: 'Aashirvaad Shudh Chakki Atta 5 KG',
    brand: 'Aashirvaad',
    barcode: '8901725111029',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 215,
    selling_price: 245,
    mrp: 275,
    wholesale_price: 238,
    min_selling_price: 230,
    gst_percent: 0,
    stock: 45,
    reserved_stock: 0,
    min_stock: 5,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    description: '100% whole wheat flour ground through traditional chakki process for soft, fluffy rotis.',
  },
  {
    id: 'prod_sugar_loose',
    category_id: 'cat_sugar_salt',
    name: 'Pure Sparkling White Sugar (Loose)',
    brand: 'Madhur',
    barcode: '8901030004016',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 41,
    selling_price: 49,
    mrp: 55,
    wholesale_price: 46,
    min_selling_price: 44,
    gst_percent: 0,
    stock: 185.000,
    reserved_stock: 0,
    min_stock: 25,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    description: 'Clean, sulphur-free white refined sugar crystals.',
  },
  {
    id: 'prod_tata_salt',
    category_id: 'cat_sugar_salt',
    name: 'Tata Salt Vacuum Evaporated Iodized 1 KG',
    brand: 'Tata',
    barcode: '8901030383821',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 22,
    selling_price: 28,
    mrp: 30,
    wholesale_price: 26,
    min_selling_price: 25,
    gst_percent: 0,
    stock: 140,
    reserved_stock: 0,
    min_stock: 20,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1518110903416-24e525141151?auto=format&fit=crop&w=600&q=80',
    description: 'Desh Ka Namak. Pure vacuum evaporated iodized salt essential for cognitive health.',
  },
  {
    id: 'prod_fortune_oil',
    category_id: 'cat_oils',
    name: 'Fortune Sunlite Refined Sunflower Oil 1 Litre',
    brand: 'Fortune',
    barcode: '8906007281015',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 112,
    selling_price: 138,
    mrp: 165,
    wholesale_price: 130,
    min_selling_price: 122,
    gst_percent: 5,
    stock: 58,
    reserved_stock: 0,
    min_stock: 10,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 1,
    photo_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    description: 'Light, healthy cooking oil enriched with Vitamins A, D & E for heart-friendly daily cooking.',
  },
  {
    id: 'prod_amul_ghee',
    category_id: 'cat_oils',
    name: 'Amul Pure Cow Ghee 500 ML Tin',
    brand: 'Amul',
    barcode: '8901262010052',
    unit: 'PIECE',
    is_loose: 0,
    purchase_cost: 295,
    selling_price: 345,
    mrp: 375,
    wholesale_price: 330,
    min_selling_price: 315,
    gst_percent: 12,
    stock: 32,
    reserved_stock: 0,
    min_stock: 6,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1631451095765-2c91616fc9e6?auto=format&fit=crop&w=600&q=80',
    description: 'Traditional aroma and granular texture, made from fresh cow milk fat.',
  },
  {
    id: 'prod_everest_chilli',
    category_id: 'cat_spices',
    name: 'Everest Tikhalal Red Chilli Powder 200g',
    brand: 'Everest',
    barcode: '8901786101124',
    unit: 'BOX',
    is_loose: 0,
    purchase_cost: 65,
    selling_price: 82,
    mrp: 95,
    wholesale_price: 78,
    min_selling_price: 72,
    gst_percent: 5,
    stock: 44,
    reserved_stock: 0,
    min_stock: 8,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    description: 'Rich red color and sharp pungent taste to liven up curries, gravies, and marinades.',
  },
  {
    id: 'prod_everest_haldi',
    category_id: 'cat_spices',
    name: 'Everest Turmeric Powder 200g',
    brand: 'Everest',
    barcode: '8901786101131',
    unit: 'BOX',
    is_loose: 0,
    purchase_cost: 52,
    selling_price: 66,
    mrp: 75,
    wholesale_price: 62,
    min_selling_price: 58,
    gst_percent: 5,
    stock: 50,
    reserved_stock: 0,
    min_stock: 8,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 0,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=600&q=80',
    description: 'Golden yellow turmeric with high natural curcumin content for health and immunity.',
  },
  {
    id: 'prod_cashews_loose',
    category_id: 'cat_dryfruits',
    name: 'Goa W240 Premium Whole Cashews / Kaju (Loose)',
    brand: 'Royal Dry Fruits',
    barcode: '8901030007017',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 680,
    selling_price: 840,
    mrp: 990,
    wholesale_price: 800,
    min_selling_price: 750,
    gst_percent: 5,
    stock: 24.500,
    reserved_stock: 0,
    min_stock: 4,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 1,
    photo_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=600&q=80',
    description: 'Crunchy, sweet, jumbo W240 cashew kernels, rich in healthy fats and zinc.',
  },
  {
    id: 'prod_almonds_loose',
    category_id: 'cat_dryfruits',
    name: 'California Badam / Almonds (Loose)',
    brand: 'Royal Dry Fruits',
    barcode: '8901030007024',
    unit: 'KG',
    is_loose: 1,
    purchase_cost: 620,
    selling_price: 760,
    mrp: 890,
    wholesale_price: 720,
    min_selling_price: 680,
    gst_percent: 5,
    stock: 31.000,
    reserved_stock: 0,
    min_stock: 5,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=600&q=80',
    description: 'Fresh 100% California almonds, packed with vitamin E and dietary fiber.',
  },
  {
    id: 'prod_tata_tea',
    category_id: 'cat_beverages',
    name: 'Tata Tea Gold Leaf 500g',
    brand: 'Tata Tea',
    barcode: '8901052002342',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 245,
    selling_price: 295,
    mrp: 340,
    wholesale_price: 280,
    min_selling_price: 265,
    gst_percent: 5,
    stock: 38,
    reserved_stock: 0,
    min_stock: 6,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    description: 'Fine CTC tea leaves blended with 15% gently rolled long leaves for exquisite aroma.',
  },
  {
    id: 'prod_bru_coffee',
    category_id: 'cat_beverages',
    name: 'Bru Instant Coffee 100g Glass Jar',
    brand: 'Bru',
    barcode: '8901030043121',
    unit: 'PIECE',
    is_loose: 0,
    purchase_cost: 165,
    selling_price: 198,
    mrp: 225,
    wholesale_price: 190,
    min_selling_price: 180,
    gst_percent: 18,
    stock: 25,
    reserved_stock: 0,
    min_stock: 5,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 0,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80',
    description: 'Rich blend of 70% coffee and 30% chicory, carefully roasted for authentic South Indian filter coffee experience.',
  },
  {
    id: 'prod_parle_g',
    category_id: 'cat_snacks',
    name: 'Parle-G Gold Glucose Biscuits 250g Family Pack',
    brand: 'Parle',
    barcode: '8901719101012',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 25,
    selling_price: 30,
    mrp: 35,
    wholesale_price: 28,
    min_selling_price: 27,
    gst_percent: 18,
    stock: 120,
    reserved_stock: 0,
    min_stock: 20,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=600&q=80',
    description: 'The taste of India! Crispy, wholesome milk and wheat glucose biscuits.',
  },
  {
    id: 'prod_amul_taaza',
    category_id: 'cat_dairy',
    name: 'Amul Taaza Toned Milk 1 Litre Tetra Pak',
    brand: 'Amul',
    barcode: '8901262010113',
    unit: 'PIECE',
    is_loose: 0,
    purchase_cost: 62,
    selling_price: 72,
    mrp: 75,
    wholesale_price: 70,
    min_selling_price: 68,
    gst_percent: 0,
    stock: 50,
    reserved_stock: 0,
    min_stock: 10,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 1,
    is_bestseller: 1,
    is_offer: 0,
    photo_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    description: 'Fresh toned milk, homogenized and UHT treated. Long shelf life, zero preservatives.',
  },
  {
    id: 'prod_surf_excel',
    category_id: 'cat_household',
    name: 'Surf Excel Easy Wash Detergent Powder 1 KG',
    brand: 'Surf Excel',
    barcode: '8901030381018',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 118,
    selling_price: 142,
    mrp: 160,
    wholesale_price: 135,
    min_selling_price: 128,
    gst_percent: 18,
    stock: 42,
    reserved_stock: 0,
    min_stock: 8,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 1,
    photo_url: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80',
    description: 'Removes tough stains like clay, oil, ink and chocolate with super clean fragrance.',
  },
  {
    id: 'prod_dettol_soap',
    category_id: 'cat_personal',
    name: 'Dettol Original Germ Protection Soap 125g (Buy 3 Get 1 Free)',
    brand: 'Dettol',
    barcode: '8901396112028',
    unit: 'PACKET',
    is_loose: 0,
    purchase_cost: 148,
    selling_price: 178,
    mrp: 199,
    wholesale_price: 170,
    min_selling_price: 162,
    gst_percent: 18,
    stock: 36,
    reserved_stock: 0,
    min_stock: 6,
    is_active: 1,
    is_visible_online: 1,
    is_pos_available: 1,
    is_featured: 0,
    is_bestseller: 1,
    is_offer: 1,
    photo_url: 'https://images.unsplash.com/photo-1607006314175-f5b2447fa0d2?auto=format&fit=crop&w=600&q=80',
    description: 'Classic pine fragrance with 99.9% germ protection for daily family hygiene.',
  },
];

export const sampleCustomers = [
  {
    id: 'cust_001',
    name: 'Ramesh Patel',
    phone: '9820123456',
    email: 'ramesh.patel@gmail.com',
    address: 'Flat 402, Royal Palms, Sector 4, Indirapuram',
    credit_balance: 450.00, // Khata udhar
    total_spent: 4890.00,
    orders_count: 8,
  },
  {
    id: 'cust_002',
    name: 'Sunita Verma',
    phone: '9811223344',
    email: 'sunita.v@yahoo.com',
    address: 'House 18, Block B, Vaishali, Ghaziabad',
    credit_balance: 0.00,
    total_spent: 8320.00,
    orders_count: 14,
  },
  {
    id: 'cust_003',
    name: 'Amitabh Sen',
    phone: '9877001122',
    email: 'asen.kol@gmail.com',
    address: 'Tower 2, Flat 904, Shipra Sun City',
    credit_balance: 120.00,
    total_spent: 2450.00,
    orders_count: 3,
  },
];

export const sampleSuppliers = [
  {
    id: 'supp_001',
    name: 'Mandi Agro Traders',
    phone: '9899112233',
    company: 'Mandi Agro Traders Pvt Ltd',
    gstin: '09AABCU9603R1ZM',
    address: 'Galla Mandi Yard 4, Sahibabad, UP',
  },
  {
    id: 'supp_002',
    name: 'Hindustan Fast Movers Wholesale',
    phone: '9810554433',
    company: 'HFM Distribution Ltd',
    gstin: '09AAACH7823E1ZP',
    address: 'Warehouse Hub 14, Mohan Nagar, Ghaziabad',
  },
];

export const sampleRecentOrders = [
  {
    id: 'ord_pos_1001',
    order_number: 'POS-1001',
    invoice_number: 'INV-000101',
    order_type: 'POS',
    status: 'DELIVERED',
    customer_name: 'Walk-in Customer',
    customer_phone: '9800000001',
    delivery_address: 'In-Store Counter Checkout',
    subtotal: 310.00,
    discount: 10.00,
    delivery_charge: 0.00,
    gst_amount: 14.50,
    total_amount: 300.00,
    payment_status: 'PAID',
    payment_method: 'CASH',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    items: [
      { product_name: 'India Gate Royal Basmati Rice (Loose)', quantity: 2.000, unit: 'KG', unit_price: 92.00, cost_price: 72.00, total_price: 184.00 },
      { product_name: 'Tata Salt Vacuum Evaporated Iodized 1 KG', quantity: 1, unit: 'PACKET', unit_price: 28.00, cost_price: 22.00, total_price: 28.00 },
      { product_name: 'Pure Sparkling White Sugar (Loose)', quantity: 2.000, unit: 'KG', unit_price: 49.00, cost_price: 41.00, total_price: 98.00 },
    ],
  },
  {
    id: 'ord_online_10245',
    order_number: 'GR-10245',
    invoice_number: 'INV-000102',
    order_type: 'ONLINE_DELIVERY',
    status: 'NEW',
    customer_name: 'Sunita Verma',
    customer_phone: '9811223344',
    delivery_address: 'House 18, Block B, Vaishali, Ghaziabad (Near Mother Dairy)',
    subtotal: 685.00,
    discount: 30.00,
    delivery_charge: 0.00, // Free above ₹499
    gst_amount: 22.80,
    total_amount: 655.00,
    payment_status: 'PAID',
    payment_method: 'UPI',
    created_at: new Date(Date.now() - 600000).toISOString(), // 10 mins ago
    items: [
      { product_name: 'India Gate Royal Basmati Rice (Loose)', quantity: 3.000, unit: 'KG', unit_price: 92.00, cost_price: 72.00, total_price: 276.00 },
      { product_name: 'Fortune Sunlite Refined Sunflower Oil 1 Litre', quantity: 2, unit: 'PACKET', unit_price: 138.00, cost_price: 112.00, total_price: 276.00 },
      { product_name: 'Unpolished Desi Toor Dal / Arhar Dal (Loose)', quantity: 1.000, unit: 'KG', unit_price: 135.00, cost_price: 110.00, total_price: 135.00 },
    ],
  },
];
